### ISSUE TITLE
Update process doesnt work, killed the app

### ISSUE THREAD

**Issue by crsnwby** [vicwomg/pikaraoke#139]
Installed the package, tried to update as per script instructions to 1.1.1 failed with error and now app wont launch automatically or via command, command error is no file exists, update error was a permissions issue.

**Comment by crsnwby** [comment]
The I see further down you cant plug in a USB MIC, so basically this is a waste of time... its just a youtube player with a phone app. All this development and I can just replace it with google casting the phone to the TV instantly.

**Comment by vicwomg** [comment]
Which update script did you run? Do you have log output?

What pikaraoke does better than chromecast:
- Queue management
- Users can access through web browser
- Change song keys
- Offline song library 
- MP3+CDG support
- No ads

If you don't need that stuff, by all means use chromecast. Also, consider that there are real people (and in many cases just one person) working on these projects and don't really like being told their hard work is a "waste of time"

**Comment by CursedDevelopment** [comment]
I have been installing it yesterday for the first time and I think I know what might have happened.
apt-get doesn't work straight from the 1.1.0 image because Ubuntu changed the update branch name from stable to oldstable on their servers.
Running `sudo apt update` did offer me to fix the issue automatically (also ran a `sudo apt upgrade` afterwards). After doing so the setup script works again as it's supposed to and PiKaraoke runs just fine afterwards.

**Comment by vicwomg** [comment]
@CursedDevelopment Thank you! 

Updating the setup pi script to this fixes it:
`sudo apt-get update --allow-releaseinfo-change`

@crsnwby should be fixed in the latest pull if feel like wasting your time.
