### ISSUE TITLE
Add VLC support

### ISSUE THREAD

**Issue by ducttapecoder** [vicwomg/pikaraoke#16]
Could you refactor and add the VLC as another supported player? There are a few benefits to it:
* more distros supported by VLC. I couldn't compile omxplayer on manjaro/arch
* VLC has a filter to change pitch via UI. I'm not sure if it could be accessed via cmd, but that is possible for a future version.
Thanks for this awesome work

**Comment by vicwomg** [comment]
I initially tried very hard to use vlc as the default player for exactly these reasons but abandoned it for reasons I can't recall. Either it didn't work well on the CLI or have a good Api for skipping/pausing tracks. But I'd be happy to revisit this when I get some time.

**Comment by petemarvin** [comment]
I made #44 pull request to add an option to use VLC player. For future improvements we can implement pitch change or tempo.

**Comment by vicwomg** [comment]
Great work @petemarvin , I merged it to develop. I made a modification to set the default audio output to alsa:hw0:0 since it threw a bunch of errors for me (I use HDMI). Raspbian will default hw0:0 to HDMI if there is audio hardware detected on the HDMI port.  

If you want to use headphone, I think we should let Raspbian handle the default audio device through:
`sudo raspi-config`
Advanced Options > Audio > Force 3.5mm (headphone) jack

In doing so, hw0:0 becomes the headphone jack. Added documentation for all of this. 

This is great though! Nice to be free of omxplayer. I'm going to try to get this to work on OSX

**Comment by petemarvin** [comment]
Great.  I was really having problem with that audio output. Maybe in the feature development, we can add in the web interface the option to set audio output for easy management.

**Comment by vicwomg** [comment]
@petemarvin I was trying to get this to work on OSX and it was very hard to get python-vlc to render a graphical window in Cocoa. I imagine there would be similar issues in Windows. Instead, I wrote a client that interfaces with the CLI version of VLC that way the OS respective window server can handle it. The client remote controls it using the built-in VLC http web server. See:

https://github.com/vicwomg/pikaraoke/blob/45-xplatform_support_and_python3/vlcclient.py

Everything is supported except for marqueeing right now. 

It would be great to get pi using the same client to prevent excessive "if" logic in the code. If you have active work on VLC would be good to sync up. I may write a similar client for omxplayer to clean things up.

**Comment by vicwomg** [comment]
now implemented in master with the --use-vlc option
