### ISSUE TITLE
URL in text and hardcode it rather than IP

### ISSUE THREAD

**Issue by bingobob** [vicwomg/pikaraoke#256]
Hi all,

Can I have the QR code generated and link to a URL of my choice (that i set somewhere). e.g. http://www.abb.com/

rather than it picking up my LAN 192 address?

Thanks

**Comment by dapuzz** [comment]
You can achieve this result with very few small changes: 
 - in templates/splash.html adjust at your glance, just look for "Connect to" row
 - in karaoke.py look for `self.url = "https://%s:%s" % (self.ip, self.port)` and replace with what you want to be shown. 

 The qr code will be reflecting same information as well.


I think this is the most quick and dirty solution, we can also pull a request to add a --url parameter in order to have it changeable programmatically,

**Comment by vicwomg** [comment]
Added in the latest pikaraoke 1.3, --url or -u option
