### ISSUE TITLE
Can't search any longer.

### ISSUE THREAD

**Issue by Rwestrem** [vicwomg/pikaraoke#26]
Worked fine 2 days ago.  I updated the YouTube url deal in the settings but still can no longer search and add songs.  Just an empty web page that says server is down or busy. Not sure what to check.  

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by vicwomg** [comment]
You are right. Looks like the public youtube-scrape search api is down. I'll give it until tomorrow to return and if it doesn't investigate deploying my own

**Comment by vicwomg** [comment]
Checked with youtube-scrape and their public heroku search api went down due to exhausting the free tier limit, so I am now hosting my own and updated the search url, which would be more flexible and I have more control over. Give it a try with the latest pull.

We'll see how it fares, I might hit the same usage cap and we might be just temporarily kicking the issue down the road. Will keep this ticket open.

**Comment by vicwomg** [comment]
as it turns out youtube-dl has a built-in search api:
```youtube-dl -j "ytsearch3:you're the best around karaoke"```

returns a json object of 3 search results. 

I think this is definitely preferred, and probably more future-proof. I'll refactor things when I get the time.

**Comment by vicwomg** [comment]
fixed in e29d1bf
