### ISSUE TITLE
Remove pygame/vlc dependency, move splash screen and video rendering to html

### ISSUE THREAD

**Issue by vicwomg** [vicwomg/pikaraoke#277]
I would very much like to remove the pygame dependency. Rendering graphics natively is nice, but the dependencies surrounding pygame are a major pain point. I think it's the main reason folks have trouble installing on different platforms. On pi alone, pulling down these libraries can take 20 minutes.

Ideally we could render the splash screen AND the video on Flask inside of an HTML page. This would be universally renderable on all windowed systems. 

In addition, maybe we can remove vlc while we're at it. It's pretty bloated for what this is doing. We can use ffmpeg to stream the video to a URL, including transposing in real-time

`ffmpeg -i <inputfile> -filter:a "rubberband=pitch=0.5" -listen 1 -f mp4 -movflags frag_keyframe+empty_moov http://localhost:8080/`

Pitch value calculation: (2^x/12), where x represents the number of semitones you would like to transpose

The splash screen has a hidden video tag which launches the video when it is queued up. 

Pros:
- Less dependencies and OS variance in behavior
- More seamless operation, we're not jumping between pygame and vlc
- Remote viewing (the pi acts as a server, any browser can view the splash screen and video)
- Much easier to work with HTML in terms of fancy UI (animations! overlays! gifs?!)

Cons:
- No longer able to run from Raspbian lite CLI. We need a window environment.
- Audio will not auto-play in most browsers unless you interact with the browser first. Firefox does allow you to toggle this permission. We might be able to work around it with selenium
-  Might be too taxing on the pi hardware

Questions:
- ~Does ffmpeg support mp3 + cdg?~ ✅ 
- ~What happens when multiple clients connect?~ The second client just hangs, doesn't affect the primarly splash screen

**Comment by Hartebee5t** [comment]
This sounds like an excellent move, although I'm a bit concerned about that third Con bullet (about pi hardware limitations).
Would that problem for a pi go away if the pitch-change was not used (or configurably disabled), or is the process-hog more inherent in ffmpeg?
Alternatively, how would a pi5 have the necessary grunt?  If so, we each just need to wait for our pre-orders to be fulfilled before we make the jump (the race is ON!)

**Comment by vicwomg** [comment]
> This sounds like an excellent move, although I'm a bit concerned about that third Con bullet (about pi hardware limitations). Would that problem for a pi go away if the pitch-change was not used (or configurably disabled), or is the process-hog more inherent in ffmpeg? Alternatively, would a pi5 have the necessary grunt? If so, we each just need to wait for our pre-orders to be fulfilled before we make the jump (the race is ON!)

I have a proof of concept going now. Seems to work on OSX. I can't imagine ffmpeg is much more CPU-intensive with rendering and pitch-shift algorithms than VLC but I could be wrong. I think they use the same codecs under the hood. 

> Wow, glad to hear this project is still going strong. Would love to see how this would be implemented.

Haha well if by "going strong" you mean I update it once a year when I'm home for the holidays and bored.

**Comment by vicwomg** [comment]
Proof of concept in the following branch
277-html_ffmpeg_video_rendering

I'm feeling really good about this direction. Interested in early feedback:

cd to your pikaraoke
`git pull`
`git checkout 277-html_ffmpeg_video_rendering`
`pip3 install requirements.txt`

You need ffmpeg and chrome installed. 

`python3 app.py`

Should launch a Chrome full-screen browser view using selenium. mp3/cdg, transposition and volume control is not yet working.

**Comment by vicwomg** [comment]
Raspberry pi notes:
- It works! You can host a server on it 
- ffmpeg video encoding is slow, best to avoid it with vcodec=copy. For other formats transcoding to mp4, it might also be acceleratable with h264 codecs enabled:  https://stackoverflow.com/questions/40175644/ffmpeg-hardware-acceleration-on-raspberry-pi
- The default download directory should change, desktop does not have access to the old directory without sudo
- Python has trouble installing requirements.txt in desktop environment "This environment is externally managed". We might have to use venv (blech). Or install them with a script and `apt-get install python3-<module>`
- Installing and updating yt-dlp is a pain in the ass. Consider migrating this to the python library so it's just another dependency
- Chromium struggles to launch in kiosk mode, need to switch to X11 in raspi-config

**Comment by vicwomg** [comment]
I mean the latter. The video player no longer needs to be on the same host
as the server.

But nothing would stop you from launching multiple instances of PiKaraoke
on the same machine on different ports to suit the use case you’re
describing.

-v

**Comment by vicwomg** [comment]
This branch is in a stable state for testing. I have checked it out on a pi4 2gb and it works great and we're at feature parity (transposition, cdg+mp3, etc)

Would appreciate some eyes from someone on a pi3 w/ raspberry pi desktop

**Comment by troy-lim** [comment]
Wow! Does this mean I can have different karaoke instance in every room in the house all from just one server? (Assuming that I have a Smart TV  in each room)

Can you give me a step-by-step instruction on how install that on a fresh Rpi3?

**Comment by vicwomg** [comment]
@frankchau93 Can you elaborate on how you're launching it as a service? The logs seem to indicate that the process is in some kind of restart loop (about every minute). So that would probably prevent it from keeping an active queue for very long if at all.

**Comment by vicwomg** [comment]
Super useful output @frankchau93 , looks like it didn't recover well from a song with some weird unicode in it:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 28: invalid start byte
```

Shaggy┬á & Ricardo Rikrok Ducent - It Wasn't Me [SC Karaoke].cdg", "Shaggy┬á & Ricardo Rikrok Ducent - It Wasn't Me [SC Karaoke].mp3"

I'll be sure to fix that. Python is really bad at unicode.

**Comment by Deastrom** [comment]
didn't get it to stream remotely, but opening chrome locally works well.

**Comment by nathanpalmer** [comment]
I love this new direction. Particularly because I was having issues getting it to compile on an Atari VCS running Elementary OS. I had the same issue on Linux Lite. 

I still can't get this branch working on the VCS though. I can post the error if you want. However, the fact that this works with a browser though makes this possibly even better. Right now I have it running from OSX on my laptop but the browser is running on the VCS through chrome in kiosk mode. It works just fine (you just can't have 2 splashes running at once.)

One thing that could help with this would be adding a `--headless` option that wouldn't try to open chrome and it would just give you the URL. I could probably just run it in a Docker container at that point and have a shortcut to open the browser (or I could autoboot it to it.) 

( Also, keep up the good work.. I was thinking I needed to build something, but then found this ;) )

**Comment by nathanpalmer** [comment]
> One thing that could help with this would be adding a --headless option that wouldn't try to open chrome and it would just give you the URL.

I just realized that this option already exists as `--hide-splash-screen`

**Comment by vicwomg** [comment]
Yes, but “—headless” is the better name I was struggling to come up with!
I’ll add that as an alias.

Please do share what dependency issues you were having with those Linux
distros.

**Comment by nathanpalmer** [comment]
Looks like it's not a dependency issue, but a runtime issue. 

```
> python3 app.py
Traceback (most recent call last):
  File "/home/nathan/pikaraoke/app.py", line 13, in <module>
    import cherrypy
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.2_1/lib/python3.11/site-packages/cherrypy/__init__.py", line 71, in <module>
    from cherrypy import _cpdispatch as dispatch  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.2_1/lib/python3.11/site-packages/cherrypy/_cpdispatch.py", line 214, in <module>
    getargspec = inspect.getargspec
                 ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

by the looks of it though, I don't see any application code there

**Comment by nathanpalmer** [comment]
Just for a follow-up. I got it working just fine after removing `python3` from linuxbrew and installing it via apt get.

One comment on my usage of it. I set it up as a startup application upon login, once you close it it closes the browser but the backend application stays running. This causes issues when it's a startup app because it's running in the background and won't open up again without a reboot. Would be nice if it detected the browser closed and automatically shutdown. Or possibly do that with a command-line option.

**Comment by nathanpalmer** [comment]
I'm mostly using the Atari VCS because I already have it ;) I'm still considering picking up a Pi for this, but wanted to make sure I have a working solution before spending the money. The VCS doesn't seem to have any performance issues, though I believe it's quite a bit more powerful than a Pi 3.

Yeah, I was just closing the browser. I'll try next time from the web app.

For headless, I would expect a different story. I would want it running all the time. I setup a docker server that's always on so I just have to open a browser to the splash URL to get the karaoke going. I don't know which option I'm going to go with so far, now that I have both working. Both require me to have a keyboard and mouse connected to the machine to start it up. (though I could maybe get around that with a dedicated pi that boots to it.)

Though I did think it would be great if the headless option was just a video stream that could be picked up by VLC. Because then I can just open the VLC app on my Apple TV and connect to the stream. I wouldn't need the Atari VCS or another Pi for this option, which could be nice. I did some experiments and could stream it from ffmpeg, very much like you're doing to the browser. But it gets tricky when you want to change the video or add overlays to it (such as who's signing next.)

**Comment by vicwomg** [comment]
@frankchau93 

I'm not sure why that might be, seems to work fine for me on the various setups I've tried. I wonder if we should always use the IP as the now_playing stream url under the hood instead of trying the hostname.

Where did you specify that ffmpeg_url exactly? Not seeing where you'd do that in the code.

**Comment by RecursiveFunctions** [comment]
> One complication, though, is that you need to interact with the browser once before it will allow videos to play. That's just a limitation in most browsers, to prevent obnoxious advertising. Currently when visiting /splash, pikaraoke will show an overlay modal explaining that, with a button to press to dismiss it. This serves as the interaction.

I think I've got a workaround for this. in addition to --kiosk, use --start-maximized when opening up chromium.
`options.add_argument("--start-maximized")
`

I just tested this on a raspberry pi 4 (8GB) with Debian GNU/Linux 12 (bookworm)

**Comment by vicwomg** [comment]
> @vicwomg 
> So far it mostly works! The only thing I noticed is, if i refresh the page or if there's something wrong, the song queue would hang and would constantly be 'paused'. There would be no way for me to skip or refresh to fix it without restarting it manually. Not sure if there's a way for me to 'reset' the queue or find a way to continue if it hangs like that.

Thanks for that, I'll add some version of this ffmpeg_url / stream_url distinction to the merge just to cover the bases of configurations like yours. Seems to work fine.  

I just merged some changes that make error recovery for page refreshes and failed streams better. There's a timeout of 10s and then it will clear that song and move on.

Getting close to merging this to main.

**Comment by vicwomg** [comment]
Merged to main

**Comment by honestlai** [comment]
I love that this is working on a separate browser, but I need to be able to proxy this through nginx and/or cloudflare and noticed when I do this, the video no longer plays. Is this a websocket issue?

**Comment by vicwomg** [comment]
Not sure, never tried a non LAN configuration. Video plays over port 5556,
make sure that’s also allowed through the firewall.

**Comment by honestlai** [comment]
Hmm... got it... proxy'ing doesn't rely on port forwarding, but it would make sense now that the video would not be delivered. I'm guessing it's TCP 5556.
