### ISSUE TITLE
[BUG] Help 😢

### ISSUE THREAD

**Issue by agentpohh214** [vicwomg/pikaraoke#302]
![IMG_20231228_095556](https://github.com/vicwomg/pikaraoke/assets/155034949/3b7ef235-42ec-49c6-9bc7-878f9ffc58ca)

Auto play disabled idk what to do and idk how to install ffmpeg , 

Device server used: RASPI 4 (Successfull installed)
Client use: Steamdeck linux/WinOS( Browser Auto play disabled)

**Comment by vicwomg** [comment]
This message is normal. You just need to click that button to dismiss it, and that counts as an interaction

**Comment by agentpohh214** [comment]
I try to play a vid , but it's not playing , it's in queueing only and it stuck in there.

**Comment by vicwomg** [comment]
What's the browser on the Steamdeck?

**Comment by agentpohh214** [comment]
Im using chrome and mozilla both are in the latest version.

Im in dual boot which is i can go to windows os , same encounter error with chrome browser. , The .bat file also nothing show up when trying to run as administrator.

**Comment by agentpohh214** [comment]
![Screenshot_2023-12-28-17-09-37-222](https://github.com/vicwomg/pikaraoke/assets/155034949/30ee8385-e0c2-498f-b57f-904bab060f33)


Here's the log , sorry i forgot to upload the log

**Comment by vicwomg** [comment]
I don't understand this screenshot. Your first post says you running the server on a pi 4 and the client is steamdeck.  Are you ssh-ing into the pi with your android device and launching pikaraoke remotely?

If you're launching the server remotely it should be headless: ./pikaraoke.sh --headless otherwise it will try to launch the splash screen.

I think you'll need to walk me through every step and all the hardware of your setup from the very beginning.
