### ISSUE TITLE
Deleted files still showing on Browse tab

### ISSUE THREAD

**Issue by iamj11** [vicwomg/pikaraoke#434]
**Describe the bug**
The deleted hidden system files are still showing on the Browse tab.

**To Reproduce**
- Connect external HDD full of songs to PC
- Delete songs (say hundreds of songs) from HDD using PC
- Reconnect HDD to Rpi and run Pikaraoke
- Click the Browse tab and Sort Alphabetically (default)
- It'll list hundreds of 8-character filenames with prefix "$"

**Expected behavior**
All filenames with prefix "$" should not be shown

**Screenshots**
![Untitled](https://github.com/user-attachments/assets/9bf3a7cf-94ee-465a-9736-cb324fb9fcac)

**Platform (please complete the following information):**
 - Hardware: RPi4 2gb
 - OS: Rpi Bookworm
 - OS version: 6.6.62
 - Browser: all 
 - Version all

    Platform: Raspberry Pi 4 Model B Rev 1.5
    OS Version: Debian 1:6.6.62-1+rpt1
    Youtube-dl (yt-dlp) version: 2024.12.06
    FFmpeg version: 5.1.6-0+deb12u1+rpt1
    Pikaraoke version: 1.6.0

**Additional context**

When I reconnect HDD to PC, all those filenames with "$" prefix arent shown. It only shows in Pikaraoke/Browse tab.

**Comment by Romeo1984** [comment]
My experience is that the library refresh is not immediate. You have to refresh the library from the admin page. Sent from my iPhoneOn Dec 8, 2024, at 8:53 AM, iamj11 ***@***.***> wrote:﻿
Describe the bug
PLEASE FILL THIS FORM OUT ENTIRELY for a response.
To Reproduce

Connect external HDD to PC
Delete songs (say hundreds of songs) from HDD using PC
Reconnect HDD to Rpi and run Pikaraoke
Click the Browse tab and Sort Alphabetically (default)
It'll list hundreds of 8-character filenames with prefix "$"

Expected behavior
All filenames with prefix "$" should not be shown
Screenshots
Untitled.png (view on web)
Platform (please complete the following information):

Hardware: RPi5 2gb
OS: Rpi Bookworm
OS version: 6.6.62
Browser: all
Version all

Additional context
When I reconnect HDD to PC, all those filenames with "$" prefix arent shown. It only shows in Pikaraoke/Browse tab.

**Comment by jepes1981** [comment]
> 
> When I reconnect HDD to PC, all those filenames with "$" prefix arent shown. It only shows in Pikaraoke/Browse tab.
>

PiKaraoke scans the directory every start-up so it should not find anything there that ended with the supported file types, see below:

karaoke.py:345
```
    def get_available_songs(self):
        logging.info("Fetching available songs in: " + self.download_path)
        types = [".mp4", ".mp3", ".zip", ".mkv", ".avi", ".webm", ".mov"]
        files_grabbed = []
        P = Path(self.download_path)
        for file in P.rglob("*.*"):
            base, ext = os.path.splitext(file.as_posix())
            if ext.lower() in types:
                if os.path.isfile(file.as_posix()):
                    logging.debug("adding song: " + file.name)
                    files_grabbed.append(file.as_posix())
```

 High probability that there are remnant files in the folder (which probably have hidden and/or system attributes). If you unplugged the drive right after deletion, there maybe a chance of incomplete flushing to disk resulting to corruption.

Try browsing the folder on raspberry showing all files `ls -a` or if using a gui file manager, ensure that hidden files are shown.

Another thing, If the file system of your drive is ntfs/vfat, run a chkdsk /f on windows (not recommended to use linux tools to fix windows file system), If on linux with ext4, `fsck.ext4`.

**Comment by iamj11** [comment]
I'm going to close this. 

Rpi somehow created a hidden "$recyclebin" folder at the root level of the external HDD that wasnt seen in Windows--even with "Show Hidden" box checked in Explorer. I was able to see it under rpi gui's File Manager and delete the folder permanently. The files had the MP4 extension which explains why Pikaraoke picked it up. I refreshed library and all is normal. Thanks y'all!
