### ISSUE TITLE
3.5mm audio output sound distortion when playing via pikaraoke

### ISSUE THREAD

**Issue by jjz03933** [vicwomg/pikaraoke#47]
I love the software! Very clean and easy to use; but I am running into an issue. I think I've isolated pretty much everything. When I play a video using pikaraoke and have the audio output via the audio port to an external speaker there is a ton of distortion and a whining sound on all the songs. Oddly enough though when I take the same mp4 file and play it directly in VLC Player on the rpi OS (not from within pikaraoke) the audio is perfectly fine (again still coming out of the audio jack to the speaker, NOT via hdmi). Is there some sort of setting that would be distorting audio only via the pikaraoke software? 

At first I assumed it was hardware and swapped out power supplies, speakers, different electric outlets, different cables. After all that I finally tried just playing the video from within VLC player and it sounds fine. I'm running on a new raspberry pi 4 (no HAT sound card) and I just installed the OS and pikaraoke today so the codebase is also new. Any thoughts?

**Comment by vicwomg** [comment]
VLC might not be a good comparison because by default pikaraoke runs omxplayer. (VLC support is in the works, but still has some kinks to work out) 

A few questions: 

**Which model Pi?** There could be a hardware revision we haven't properly tested.
**What if you open the file in omxplayer, still distorted?** Pikaraoke uses omxplayer by default
**Is it distorted over HDMI?** Would indicate if the problem is isolated to the audio out
**If you use the web interface to turn down the volume from the main pikaraoke screen, does it improve?** It could be that the default audio volume is set too high for some reason.
**If you run "amixer" on the terminal, what's the output?** This program sets the sound levels of your hardware. It would be interesting to know if the playback volume is out of whack

**Comment by vicwomg** [comment]
Thanks for all the details. I'll have to try this all out when my pi4 comes in, and figure out if we need to yet another command line option (alsa-fix-fix?)

You could also use --alsa-fix and use raspi-config to set your audio device to headphone jack only. Advanced Options > Audio > Force 3.5mm (headphone). I recall that being necessary for VLC to work un some cases. Starting to think it may be best to just let the OS handle the default audio output.

**Comment by jjz03933** [comment]
No problem. Yeah it's still odd why the "both" setting makes the audio sound so bad. I'm interested to see if yours does the same when you get your pi4.  

A little more about my hardware setup: I have the pi hooked into my tv (hdmi) which then has audio out from the tv, via optical connector, to a sound bar. The tv speakers themselves are off and the output for all TV audio is the sound bar.

**Comment by Hartebee5t** [comment]
> I'll have to try this all out when my pi4 comes in, and figure out if we need to yet another command line option (alsa-fix-fix?)

Rather than another command-line option, what about changing alsa-fix from a discrete option to an alsa-select output option that the user can provide the output pcm name as an argument (defaulting to "hw:0,0", but "both" or any user-defined device name could be passed)?  This would be kind-of consistent with something you'd said in a reply under Issue #20 

> If that works let me know and I can add a command line option for bluetooth.  

I have a named bluetooth speaker pcm set up and every time I update PiKaraoke I've to hack the karaoke.py file to embed my output option name into the play_file routine. It'd be great to just have to quote it on the command line when invoking the app.

(Mind you, now that VLC is available it looks like that just picks up whatever output option I had last used with VLC anyway)

**Comment by vicwomg** [comment]
I'm seeing the same issue on the pi 4. I'm thinking you're right. An input command argument would allow for the most flexibility. Omxplayer is wildly inconsistent across hardware. It's a bummer, but if vlc ends up to be more performant and reliable maybe we'll just drop support for omxplayer.

**Comment by vicwomg** [comment]
I have added the --adev option to the CLI. Now you can do:
`python app.py --adev alsa`
or whatever you want. The documentation gives examples for the various possibilities

**Comment by Hartebee5t** [comment]
Excellent!  Thanks, and much kudos for the lightning-fast turnaround too!
I'll try this out later.

Regarding omxplayer, given your (I believe) original intent that this app should be able to run on early versions of Pi, perhaps omxplayer could be the baseline/fall-back player for those lesser-powered hosts, while VLC's extra features are available for the later, more-capable Pi versions and the recently-enabled 'other' platforms.

**Comment by petemarvin** [comment]
> I have added the --adev option to the CLI. Now you can do:
> `python app.py --adev alsa`
> or whatever you want. The documentation gives examples for the various possibilities

I believe the --adev command works for omxplayer. Would it be possible to work it also with vlc? I tried edting vlcclient.py and added vlc parameters
```
"--aout", "alsa",
"--alsa-audio-device","hw:0,0",
```

**Comment by Hartebee5t** [comment]
Yes, I can confirm that --adev works as advertised with omxplayer (at least, it works with 
alsa:<pcm_device_name> as the argument)

I also agree with petemarvin about having the option for vlc too. My previous finding that vlc just remembered the last audio device used with it is not always correct.

**Comment by vicwomg** [comment]
The issue as described has been addressed. File additional ticket if you'd like to see something specific to vlc.
