### ISSUE TITLE
Multiple stack traces when running app.py

### ISSUE THREAD

**Issue by jjz03933** [vicwomg/pikaraoke#56]
Hello - I've successfully installed the app on other OS's and I just tried to do so on windows 10.. I ran into a number of issues but finally got through most of them but now I'm getting some stack traces when running the app. The splash screen does in fact load but I'm unable to go to the IP address (while on the network) and debug logging shows a number of errors. I will say this is a new computer so I don't know if I installed the correct visual studio components; there seem to be a ton of option. I installed the C++ redistributable files from 2010, 2012, 2013, 2015-2019. Attached are the errors I'm receiving.
![Screenshot (1)](https://user-images.githubusercontent.com/11708889/97767298-aefa1e80-1af1-11eb-889e-dae9486987f8.png)
![Screenshot (2)](https://user-images.githubusercontent.com/11708889/97767300-b02b4b80-1af1-11eb-9779-bee563d373ae.png)
![Screenshot (3)](https://user-images.githubusercontent.com/11708889/97767302-b0c3e200-1af1-11eb-9044-0ce28df49e96.png)

**Comment by EdFabre** [comment]
@jjz03933 I haven't tested on Win X yet, but will check it out.

Overall, The current build of pikaraoke app is not currently working due to a [DMCA Takedown](https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md) of a critical tool.

I know @vicwomg is well aware of the situation. I have also been investigating a tentative fix that should fix some things. Will do a PR soon.

**Comment by jjz03933** [comment]
@EdFabre I did see the DCMA issue but I was under the impression that was specifically an issue with searching YouTube via youtube-dl.. I think this is specific to installation dependencies. I'm curious to know specifically what visual studio components are needed because I think that's the only thing didn't specifically say what was needed. I do have it running on another laptop with windows 10 so I know it at least works on the OS.

**Comment by EdFabre** [comment]
The youtube-dl this app uses is actually throwing errors during both search and downloading. I have created a Pull Request which fixes this.

Your errors are showing NameError, in my experience, that is merely a session error. Are you able to navigate to http://localhost:5000 at all?

**Comment by jjz03933** [comment]
@EdFabre I can get to localhost:5000 on the same machine that it's running on but can't hit the local IP on that port from my phone. But even on the local machine, the splash screen shows up and then if I queue something up it seems like it tries to play it but it doesn't actually play and throws more errors in the console. It very briefly shows the song in the 'now playing' area but the splash screen never loads the video and then the now playing area shortly thereafter shows that nothing is playing.
![Screenshot (4)](https://user-images.githubusercontent.com/11708889/97782118-18b41000-1b66-11eb-9954-bf40edc29703.png)

**Comment by EdFabre** [comment]
@jjz03933 Let's try a 3-pronged attack here. 

**1. Web Access**
If you can see the app locally, but not remote, it may be due to firewall settings. Try disabling your Windows Firewall to test that theory.

**2. Shell Execution**
Also, in your screenshots, I see your PowerShell doesn't indicate it was "Run as administrator". Right-click the binary and run as administrator before launching the pikaraoke app.

**3. Update Youtube-DL**
I would suggest that you update your youtube-dl using the two commands below
```
pip3 uninstall youtube-dl -y
pip3 install -U git+https://github.com/l1ving/youtube-dl
echo done
```

**Comment by vicwomg** [comment]
Pretty sure those initial exceptions are due to having a separate web browser open on the nowplaying screen before the web karaoke instance has actually started, so the commands will fail. I think it can be ignored. They are harmless, and I bet they go away if you don't have a browser open while launching app.py.

As for not being able to access via phone:
- Windows firewall blocking port 5000?
- Phone not on the same wifi?
- What is the IP address displayed on the splash screen? I think there might be issues with ipv6

**Comment by jjz03933** [comment]
@EdFabre thanks for the ideas; I think the firewall was blocking local access; I got that working. I did try the other ideas but for some reason the "now playing" song seems to start and then just disappears in a couple seconds. I've attached a video of what's happening.  Sorry, had to attach a zip because github wouldn't take mp4 
[PiKaraoke - Home - Google Chrome 2020-11-01 20-06-12.zip](https://github.com/vicwomg/pikaraoke/files/5472282/PiKaraoke.-.Home.-.Google.Chrome.2020-11-01.20-06-12.zip)

**Comment by vicwomg** [comment]
Failure seems to be in the playing of the file.

Just checking: have you installed vlc? 
If so, what happens when you try to play the files manually on vlc, do they work?

**Comment by jjz03933** [comment]
@vicwomg I thought the same thing about playing. VLC is installed and yes the files do play in VLC separately. I doubt it matters but I'm specifying -d "D:/" and d drive is a usb drive with the videos

**Comment by vicwomg** [comment]
Did you try running the full vlc command I mentioned though? There might be something in there that is being blocked. For example, the vlcclient  runs a remote control server on port 5002, among other things.

**Comment by jjz03933** [comment]
@vicwomg sorry I don't see a vlc command in the previous comments; can you resend it please?

**Comment by vicwomg** [comment]
It's in your log output. you need to cut and paste it yourself since I cannot do so from a screenshot. See the line "INFO: VLC command base: "

**Comment by jjz03933** [comment]
@vicwomg oh ok I'll do that and get back to you

**Comment by jjz03933** [comment]
@vicwomg this is what I get; just doesn't actually do anything, it just shows >> for the command line prompt
![Screenshot (5)](https://user-images.githubusercontent.com/11708889/97823944-86585d00-1c88-11eb-9485-a0c8a2aa40fc.png)

**Comment by vicwomg** [comment]
ah, so I fired up my windows machine and duplicated your usb drive setup. 

Specify your -d option like this " -d D:\ " and it should work. Gotta have that backslash in MS-DOS

**Comment by jjz03933** [comment]
@vicwomg That worked! All that for a mere windows path syntax issue. Thanks for your help! I'll be contributing on your paypal.
