### ISSUE TITLE
Splash screen remains up while song is playing

### ISSUE THREAD

**Issue by lbuchieri** [vicwomg/pikaraoke#64]
Program works fine when using --hide-splash-screen. But when splash screen comes up and you que a song, you see the 'next up' notification in the bottom corner, and then you hear the song playing, but the splash screen doesn't go away.

**Comment by vicwomg** [comment]
Can you tell me more about your setup? Platform, OS, desktop/CLI

**Comment by lbuchieri** [comment]
Raspberry Pi 3. I was not using --use-vlc when I first experienced it. I tried using that, and it didn't change anything. Still hearing the sound, but staring at splash screen.

**Comment by vicwomg** [comment]
Raspbian version? Are you running it from the Desktop GUI or directly from the command line? Working on trying to reproduce this issue.

**Comment by lbuchieri** [comment]
Fresh flash of PI OS Lite, command line only.

**Comment by vicwomg** [comment]
Thanks for the report, it's been a while since I tested on a fresh raspbian lite, so I think there are some issues with the newest versions.

I just got started with a fresh raspbian, and I'm seeing issues related to the default version of pygame, though they are not this problem exactly. I was able to resolve them by uninstalling and reinstalling ver. 1.9.6

Do you mind trying that and letting me know if this fixes it? 

```sudo pip3 uninstall pygame
sudo pip3 install pygame==1.9.6
```

Also, noticed that lite was missing libSDL, so you might have to do this as well:

```sudo apt-get install libsdl2-ttf-dev
```

Let me know if any of those things work

**Comment by lbuchieri** [comment]
That did it!

Thanks a ton!

**Comment by vicwomg** [comment]
awesome, thanks again for the report. The master branch has this fix baked into the setup script now.
