### ISSUE TITLE
Large libraries are slow-loading and difficult to navigate

### ISSUE THREAD

**Issue by scottackerson** [vicwomg/pikaraoke#85]
Now that CDGs are supported and libraries will seemingly grow, the search UX gets pretty busy, especially on mobile.  

A few suggestions:

- It would be a better user experience to distinguish local files searches from YouTube file searches to reduce confusion of what the system is doing  
- On iOS, you only get to see approximately 3 songs because the keyboard takes up ~1/3 of the display.  Perhaps make search results not inline?  

![IMG_6EB402778F13-1](https://user-images.githubusercontent.com/285904/103425816-8dadc100-4b7a-11eb-979f-74cf36991474.jpeg)

**Comment by vicwomg** [comment]
To your first point: the autocomplete dropdown is only local files (local downloaded files and mp3+g). You only see Youtube search results by clicking the search results, and then they show below the search box. So they are separate. Unless you mean something else.

**Comment by vicwomg** [comment]
I think I understand better what you're asking. It actually used to be that way: a separate search vs add box. But at some point the decision was made to combine them to make a cleaner UI. Not sure I still stand by this decision. It can be confusing and also the code is a mess. I'm now even leaning towards a separate page entirely for adding songs.

**Comment by scottackerson** [comment]
Yeah, I think there is some UX confusion with using the same search input having two different functions: inline results are for local and clicking search is for YouTube.  It's confusing because the standard search paradigm has an input box on left and search button on right for a single search function.  

Separating the search workflows would be ideal here and would enable a more streamlined song management experience that issue [86](https://github.com/vicwomg/pikaraoke/issues/86) is bringing up.

Searching local files should produce a result page that is the same template as the browse page, just isolated to the search results.

**Comment by vicwomg** [comment]
It occurs to me that the reason search/add are combined is so that you wont keep adding duplicate tracks. While you type the name of a song, you will be presented with autocomplete results of the existing library. Then if it's already there, you wont go adding it again. 

As such, I will leave the combo search box for now, but I have added some optimizations to the autocomplete dropdown to make it more visible on mobile devices. It will now auto-scroll to top on focus, and the font size is smaller allowing the autocomplete search results to display more fully.

**Comment by mbreughe** [comment]
This may be related, but I also noticed for local databases of 100K+ files, accessing the songs, or using the search functions gets really slow. Maybe caching file names could help.

**Comment by vicwomg** [comment]
I'd love to hear more and some more details numbers for what you're talking about @mbreughe . Library size, approx load times, which pages, what happens while its loading. 

I haven't encountered 100K libraries yet, but I was sure it would happens sooner or later and that pikaraoke would struggle with them.

**Comment by mbreughe** [comment]
Hi @vicwomg, thanks for your reply. I did some quick debugging (--log-level 1), but couldn't find a definite answer. Unfortunately when I use cProfile, pikaraoke doesn't work properly anymore. Instead I tried to use the timestamps on the logging messages to get a rough idea where the slowdown comes from

What I can tell from the debugging is that the get_available_songs() method is actually pretty fast, regardless of the library size (took 2 seconds).

After the message "Starting PiKaraoke" I don't get anything anymore, which only tells me that it is not karaoke.py, but the web front end that is hanging:


[2021-01-23 22:18:31] DEBUG: Fetching available songs in: unique_songs/
[2021-01-23 22:18:33] DEBUG: done fetching
[2021-01-23 22:18:34] DEBUG: Killing old VLC processes
[2021-01-23 22:18:34] DEBUG: Generating URL QR code
[2021-01-23 22:18:34] INFO: VLC command base: /usr/bin/vlc -f --play-and-exit --extraintf http --http-port 5002 --http-password tiBvhx69k7Pg1SQhBEGZR9Zuz8QkxRD4 --no-embedded-video --no-keyboard-events --no-mouse-events --mouse-hide-timeout 0 --video-on-top --no-video-title --mouse-hide-timeout 0
[2021-01-23 22:18:34] DEBUG: Initializing pygame
[2021-01-23 22:18:34] DEBUG: Initializing screen mode
[2021-01-23 22:18:34] DEBUG: Done initializing splash screen
[2021-01-23 22:18:34] DEBUG: Rendering splash screen
[23/Jan/2021:22:18:34] ENGINE Bus STARTING
[2021-01-23 22:18:34] INFO: [23/Jan/2021:22:18:34] ENGINE Bus STARTING
[23/Jan/2021:22:18:34] ENGINE Started monitor thread '_TimeoutMonitor'.
[2021-01-23 22:18:34] INFO: [23/Jan/2021:22:18:34] ENGINE Started monitor thread '_TimeoutMonitor'.
[23/Jan/2021:22:18:34] ENGINE Serving on http://0.0.0.0:5000
[2021-01-23 22:18:34] INFO: [23/Jan/2021:22:18:34] ENGINE Serving on http://0.0.0.0:5000
[23/Jan/2021:22:18:34] ENGINE Bus STARTED
[2021-01-23 22:18:34] INFO: [23/Jan/2021:22:18:34] ENGINE Bus STARTED
[2021-01-23 22:18:34] INFO: Starting PiKaraoke!
[2021-01-23 22:18:44] WARNING: ESC pressed: Exiting pikaraoke...
[23/Jan/2021:22:18:45] ENGINE Bus STOPPING
[2021-01-23 22:18:45] INFO: [23/Jan/2021:22:18:45] ENGINE Bus STOPPING
[23/Jan/2021:22:19:07] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 5000)) shut down
[2021-01-23 22:19:07] INFO: [23/Jan/2021:22:19:07] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 5000)) shut down
[23/Jan/2021:22:19:07] ENGINE Stopped thread '_TimeoutMonitor'.
[2021-01-23 22:19:07] INFO: [23/Jan/2021:22:19:07] ENGINE Stopped thread '_TimeoutMonitor'.
[23/Jan/2021:22:19:07] ENGINE Bus STOPPED
[2021-01-23 22:19:07] INFO: [23/Jan/2021:22:19:07] ENGINE Bus STOPPED
[23/Jan/2021:22:19:07] ENGINE Bus EXITING
[2021-01-23 22:19:07] INFO: [23/Jan/2021:22:19:07] ENGINE Bus EXITING
[23/Jan/2021:22:19:07] ENGINE Bus EXITED
[2021-01-23 22:19:07] INFO: [23/Jan/2021:22:19:07] ENGINE Bus EXITED

**Comment by jramboz** [comment]
I have an approximately 90K songs library. After some testing on both my RPi 4 and my Mac, it looks like the problem with large libraries is on the front-end (browser) side. It seems there's too much data being passed for the browser to hold in memory.

First, I tested loading the files into a Python shell using glob(). Loading the file list took approximately 30 seconds on the Pi and less than a second on the Mac. Note that in both cases, the song library was on an external SSD attached to USB3, so that may have impacted loading times.

With the library loaded into pikaraoke, opening the browse page takes upwards of 60 seconds, and causes the browser to freeze at intervals. Desktop Safari on the Mac gives a warning that the webpage is using significant memory and slowing down the system. It does, however, seem to actually load the whole list.

The search page loads with significant delay, but only displays a regular dropdown in place of the text search. This occurs on both iOS Safari and desktop Safari. Attempting to open the dropdown again causes the browser to freeze on both systems. Also, I'm never prompted to enter a name and the advanced search options are displayed regardless of whether the box is checked.

I also tried loading the web interface in desktop Chrome. Chrome takes approximately 30 seconds to load the search page, which does seem to work as normal once loaded (including prompting for name). Searching YouTube also works, but again there's a delay of about 30 seconds for the page to load after the search is submitted. The browse page behavior was the same (intermittently non-responsive) as in Safari. iOS Chrome results appear identical to iOS Safari.

As stated above, all this leads me to believe that the problem is how the browser handles (or rather, doesn't) such a large amount of data being loaded into a single page. For searches, local search results may need to be handled on the server side and passed back to the client--either as a new page or via Ajax calls. For browsing, maybe the results could be paginated, either by total number of pages or by letter?

I hope this helps!

**Comment by vicwomg** [comment]
All very helpful suggestions. Yes I was thinking paging or endless scroll
is probably best for the browse screen. No browser can handle that kind of
data in a single html file.
Search might be trickier since I think the delay is coming from fully
populating the autocomplete results. I think you're right that this
probably needs to be a realtime ajax call.

I knew I'd open the floodgates of gigantic library hell when I added cdg
support 😂

**Comment by jramboz** [comment]
For pagination support, looks like [flask-paginate](https://github.com/lixxu/flask-paginate) might be an easy way to get it going. (Easy if you understand more than the bare basics of Flask, that is, unlike me!)

**Comment by vicwomg** [comment]
I think I'm in a good place with the loading issues. 

Pikaraoke now does the following:
- Only fetches/shows 500 max per page on browse screen, with proper paging controls
- Filter by letter now navs to a page with **only** results starting with letter (was just an anchor link)
- uses AJAX to realtime fetch autocomplete results after typing 2 chars, rather than just loading the entire library into the options

I'd appreciate if some of you folks with mega-libraries would retest with the latest on the development branch and let me know how it looks.

**Comment by jramboz** [comment]
After a quick test, it's working great with my large library. Both search and browse are nice and speedy. Great job!

**Comment by mbreughe** [comment]
Nice work, @vicwomg ! My library is loading smoothly now.

(FYI the update on the dev branch also fixed another issue I had with a "limit" of 5 youtube songs per session)
